name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          branch: "main"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tmforum"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # HEROKU_API_KEY and HEROKU_EMAIL will need to be set in repository secrets